name: thechemmeister
favicon: null
layout_spectrum: 0.5577898300252855
typography_spectrum: 0.04825842613354325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.07015296746976674
  lightness: 0.7213882319629192
  saturation: 0.4017443878110498
  rhythmicContrast: 0.45163827016949654
purpose: []
